name: publish
on: [push]
jobs:
publish-http-echo-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build http-echo Docker image
run: |
       docker build . --tag ghcr.io/attiand/http-echo:latest
       docker push ghcr.io/ghcr.io/attiand/http-echo:latest

